/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Front.Peliculas;

import java.awt.BorderLayout;

/**
 *
 * @author matia
 */
public class MostrarPeliculasTodas extends javax.swing.JPanel {

    /**
     * Creates new form MostrarPeliculas
     */
    public MostrarPeliculasTodas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlReco = new javax.swing.JPanel();
        pnlAccion = new javax.swing.JPanel();
        pnlAventuras = new javax.swing.JPanel();
        pnlTerror = new javax.swing.JPanel();
        pnlInfantil = new javax.swing.JPanel();
        pnlDrama = new javax.swing.JPanel();
        pnlDeporte = new javax.swing.JPanel();
        pnlSuspenso = new javax.swing.JPanel();
        pnlCFiccion = new javax.swing.JPanel();
        pnlMusical = new javax.swing.JPanel();
        pnlLatin = new javax.swing.JPanel();
        pnlDocumental = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlRecoLayout = new javax.swing.GroupLayout(pnlReco);
        pnlReco.setLayout(pnlRecoLayout);
        pnlRecoLayout.setHorizontalGroup(
            pnlRecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        pnlRecoLayout.setVerticalGroup(
            pnlRecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        PanelModificable mod = new PanelModificable("Accion");
        mod.setSize(880, 200);
        mod.setLocation(0, 0);
        pnlAccion.removeAll();
        pnlAccion.add(mod, BorderLayout.CENTER);
        pnlAccion.revalidate();
        pnlAccion.repaint();

        javax.swing.GroupLayout pnlAccionLayout = new javax.swing.GroupLayout(pnlAccion);
        pnlAccion.setLayout(pnlAccionLayout);
        pnlAccionLayout.setHorizontalGroup(
            pnlAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlAccionLayout.setVerticalGroup(
            pnlAccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlAventurasLayout = new javax.swing.GroupLayout(pnlAventuras);
        pnlAventuras.setLayout(pnlAventurasLayout);
        pnlAventurasLayout.setHorizontalGroup(
            pnlAventurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlAventurasLayout.setVerticalGroup(
            pnlAventurasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlTerrorLayout = new javax.swing.GroupLayout(pnlTerror);
        pnlTerror.setLayout(pnlTerrorLayout);
        pnlTerrorLayout.setHorizontalGroup(
            pnlTerrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlTerrorLayout.setVerticalGroup(
            pnlTerrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlInfantilLayout = new javax.swing.GroupLayout(pnlInfantil);
        pnlInfantil.setLayout(pnlInfantilLayout);
        pnlInfantilLayout.setHorizontalGroup(
            pnlInfantilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlInfantilLayout.setVerticalGroup(
            pnlInfantilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlDramaLayout = new javax.swing.GroupLayout(pnlDrama);
        pnlDrama.setLayout(pnlDramaLayout);
        pnlDramaLayout.setHorizontalGroup(
            pnlDramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlDramaLayout.setVerticalGroup(
            pnlDramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlDeporteLayout = new javax.swing.GroupLayout(pnlDeporte);
        pnlDeporte.setLayout(pnlDeporteLayout);
        pnlDeporteLayout.setHorizontalGroup(
            pnlDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlDeporteLayout.setVerticalGroup(
            pnlDeporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlSuspensoLayout = new javax.swing.GroupLayout(pnlSuspenso);
        pnlSuspenso.setLayout(pnlSuspensoLayout);
        pnlSuspensoLayout.setHorizontalGroup(
            pnlSuspensoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlSuspensoLayout.setVerticalGroup(
            pnlSuspensoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlCFiccionLayout = new javax.swing.GroupLayout(pnlCFiccion);
        pnlCFiccion.setLayout(pnlCFiccionLayout);
        pnlCFiccionLayout.setHorizontalGroup(
            pnlCFiccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlCFiccionLayout.setVerticalGroup(
            pnlCFiccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMusicalLayout = new javax.swing.GroupLayout(pnlMusical);
        pnlMusical.setLayout(pnlMusicalLayout);
        pnlMusicalLayout.setHorizontalGroup(
            pnlMusicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlMusicalLayout.setVerticalGroup(
            pnlMusicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlLatinLayout = new javax.swing.GroupLayout(pnlLatin);
        pnlLatin.setLayout(pnlLatinLayout);
        pnlLatinLayout.setHorizontalGroup(
            pnlLatinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlLatinLayout.setVerticalGroup(
            pnlLatinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlDocumentalLayout = new javax.swing.GroupLayout(pnlDocumental);
        pnlDocumental.setLayout(pnlDocumentalLayout);
        pnlDocumentalLayout.setHorizontalGroup(
            pnlDocumentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlDocumentalLayout.setVerticalGroup(
            pnlDocumentalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAventuras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTerror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInfantil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSuspenso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCFiccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDrama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDeporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLatin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDocumental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMusical, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlReco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(pnlAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlAventuras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlTerror, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlInfantil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlSuspenso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCFiccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDrama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlLatin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDocumental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlMusical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2890, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlAccion;
    private javax.swing.JPanel pnlAventuras;
    private javax.swing.JPanel pnlCFiccion;
    private javax.swing.JPanel pnlDeporte;
    private javax.swing.JPanel pnlDocumental;
    private javax.swing.JPanel pnlDrama;
    private javax.swing.JPanel pnlInfantil;
    private javax.swing.JPanel pnlLatin;
    private javax.swing.JPanel pnlMusical;
    private javax.swing.JPanel pnlReco;
    private javax.swing.JPanel pnlSuspenso;
    private javax.swing.JPanel pnlTerror;
    // End of variables declaration//GEN-END:variables
}
